abstract: A Perl/XS implementation of package-related utilities
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Package-Util
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
version: 0.01
